export const CREATE_POST = 'POST/CREATE_POST';
export const FETCH_POST = 'POST/FETCH_POST';
export const REQUEST_POST = 'POST/REQUEST_POST';
export const FETCH_POST_PAGINATION = 'POST/FETCH_POST_PAGINATION';

export const CHANGE_URL = 'APP/CHANGE_URL';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';

export const TASKS_FETCH_DATA_SUCCESS = 'TASKS_FETCH_DATA_SUCCESS';
export const NEXT_PAGE = 'NEXT_PAGE';